language: python
script:
- ssh start_docker@asperitys.com 'mkdir -p /data/csgo'
- ls -lah
- scp -r . start_docker@asperitys.com:/data/csgo/
- ssh start_docker@asperitys.com 'cd /data/csgo && docker-compose up -d'
- exit
branches:
  only:
  - main
addons:
  ssh_known_hosts:
  - asperitys.com
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
