language: python
script: 
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - ssh $MYSECRETUSER@asperitys.com hostmame
branches:
  only:
  - main

