language: python
script:
#- which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
#- eval $(ssh-agent -s)
#- echo $SSH_PRIVATE_KEY
#- echo $SSH_PRIVATE_KEY | tr -d '\r' | ssh-add -
- ssh start_docker@asperitys.com 'mkdir -p /data/csgo'
- ls -lah
- scp -r . start_docker@asperitys.com:/data/csgo/
- ssh start_docker@asperitys.com 'cd /data/csgo && docker-compose up -d'
- exit
branches:
  only:
  - main
before_install:
- openssl aes-256-cbc -K $encrypted_3fb5f5304c72_key -iv $encrypted_3fb5f5304c72_iv
  -in my_start_docker.enc -out my_start_docker -d
addons:
  ssh_known_hosts:
    - asperitys.com
