---
version: '3.3'
services:
  standalone-chrome:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    networks:
      selenium:
    volumes:
      - /dev/shm:/dev/shm 
    dns:
      - 8.8.8.8


  csgo:
    build: .
    ports:
      - 5000:5000
    networks:
      outside-network:
      selenium:
    dns:
      - 8.8.8.8
networks:
  outside-network:
    external:
      name: outside-network
  selenium:
    driver: bridge