---
version: '3'

services:
  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    networks:
      selenium:
  csgo:
    build: .
    ports:
      - 5000:5000
    networks:
      outside-network:
networks:
  outside-network:
    external:
      name: outside-network
  selenium:
    driver: bridge